language: python
python:
    - "2.7"

install: make install-deps

matrix:
    include:
      - python: "2.7"
        env: TOX_ENV=js-lint,py-lint
        install:
            - pip install tox
            - npm install -g jshint
        script: tox -e $TOX_ENV
      - python: "3.6"
        env: TOX_ENV=js-firefox
        addons:
            firefox: latest
        install:
            - wget https://github.com/mozilla/geckodriver/releases/download/v0.21.0/geckodriver-v0.21.0-linux64.tar.gz
            - mkdir geckodriver
            - tar -xzf geckodriver-v0.21.0-linux64.tar.gz -C geckodriver
            - export PATH=$PATH:$PWD/geckodriver
            - pip install tox
        script: tox -e $TOX_ENV

script:
    - python manage.py test

notifications:
    irc:
        channels:
            - "ircs://irc.megworld.co.uk:9000#subscribae"
        use_notice: true

sudo: false
