matrix:
    include:
      - language: python
        python: "2.7"
        env: TOX_ENV=lint
      - language: python
        python: "2.7"
        script: make tests-py-coverage
        after_script:
          - pip install codecov
          - codecov
      - language: node_js
        node_js: node
        env:
          - GRUNT_TASK=karma:firefox
          - MOZ_HEADLESS=1
          - FIREFOX=esr
        after_script:
          - npm install codecov
          - npx codecov
        addons:
            firefox: latest-esr
      - language: node_js
        node_js: node
        env:
          - GRUNT_TASK=karma:firefox
          - MOZ_HEADLESS=1
          - FIREFOX=latest
        after_script:
          - npm install codecov
          - npx codecov
        addons:
            firefox: latest
      - language: node_js
        node_js: node
        env: GRUNT_TASK=karma:chrome
        after_script:
          - npm install codecov
          - npx codecov
        addons:
            chrome: stable
      - language: node_js
        node_js: node
        env: GRUNT_TASK=jshint

install: if [[ $TOX_ENV ]]; then pip install tox; elif [[ $GRUNT_TASK ]]; then npm install; fi
script: if [[ $TOX_ENV ]]; then tox -e $TOX_ENV; elif [[ $GRUNT_TASK ]]; then npx grunt $GRUNT_TASK; fi

notifications:
    irc:
        channels:
            - "ircs://irc.megworld.co.uk:9000#subscribae"
        use_notice: true

sudo: false
