language: python

matrix:
    include:
      - python: "2.7"
        env: TOX_ENV=js-lint,py-lint
        before_install:
            - npm install -g jshint
      - python: "3.6"
        env: TOX_ENV=js-firefox
        addons:
            firefox: latest
        before_install:
            - npm install
            - wget https://github.com/mozilla/geckodriver/releases/download/v0.24.0/geckodriver-v0.24.0-linux64.tar.gz
            - mkdir geckodriver
            - tar -xzf geckodriver-v0.24.0-linux64.tar.gz -C geckodriver
            - export PATH=$PATH:$PWD/geckodriver
      - python: "2.7"
        env: TOX_ENV=py27

install: pip install tox
script: tox -e $TOX_ENV

notifications:
    irc:
        channels:
            - "ircs://irc.megworld.co.uk:9000#subscribae"
        use_notice: true

sudo: false
