application: subscribae
version: debug
runtime: python27
api_version: 1
threadsafe: true

default_expiration: "366d"

handlers:

- url: /_ah/(clearsessions|mapreduce|queue|warmup|start|stop).*
  script: subscribae.wsgi.application
  login: admin
  secure: always

- url: /_ah/internalupload.*
  script: subscribae.wsgi.application
  secure: always

- url: /static
  static_dir: static/
  secure: always

- url: /.*
  script: subscribae.wsgi.application
  secure: always

skip_files:
    - (.*)\.pyc
    - Gruntfile.js
    - Makefile
    - README.md
    - \.coverage(.*)
    - \.git
    - \.storage.*
    - \.tox
    - coverage
    - frontend
    - htmlcov
    - install_deps
    - karma.conf.js
    - manage.py
    - node_modules
    - original_images
    - package-lock.json
    - package.json
    - requirements\*
    - sitepackages/dev*
    - tox.ini
