application: subscribae
version: 1
runtime: python27
api_version: 1
threadsafe: true

default_expiration: "366d"

handlers:

- url: /_ah/(clearsessions|mapreduce|queue|warmup|start|stop).*
  script: subscribae.wsgi.application
  login: admin
  secure: always

- url: /_ah/internalupload.*
  script: subscribae.wsgi.application
  secure: always

- url: /static
  static_dir: static/
  secure: always

- url: /.*
  script: subscribae.wsgi.application
  secure: always

skip_files:
    - manage.py
    - README.md
    - install_deps
    - requirements.txt
    - sitepackages/dev*
    - \.storage.*
    - \.git
    - (.*)\.pyc
