#!/usr/bin/env python2
"""
Freeze production dependencies
"""

from pkg_resources import WorkingSet, RequirementParseError
from pip import FrozenRequirement
import os
import pkg_resources
import sys

base_dir = os.path.abspath(os.path.dirname(__file__))
prod_dir = os.path.join(base_dir, 'sitepackages', 'prod')

working_set = WorkingSet([prod_dir])

for dist in working_set:
    try:
        req = FrozenRequirement.from_dist(dist, [])
    except RequirementParseError:
        print 'Could not parse %s' % dist.project_name >> sys.stderr
        continue

    print str(req),
